name: Release

on:
  push:
    branches:
      - "release"

jobs:
  create-release:
    permissions:
      contents: write
    runs-on: ubuntu-20.04
    outputs:
      release_id: ${{ steps.create-release.outputs.result }}
      change_log: ${{ steps.changelog.outputs.clean_changelog }}
      version: ${{ steps.changelog.outputs.version }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Conventional Changelog Action
        id: changelog
        uses: ./.github/workflows/custom-changelog
        with:
          github-token: ${{ secrets.github_token }}
          
      - name: Set Release Enviroment Variables
        run: |
          echo "RELEASE_TAG=${{ steps.changelog.outputs.tag }}" >> $GITHUB_ENV
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "RELEASE_LOG<<$EOF" >> $GITHUB_ENV
          echo "${{ steps.changelog.outputs.clean_changelog }}" >> $GITHUB_ENV
          echo "$EOF" >> $GITHUB_ENV
          echo "Release Tag: $RELEASE_TAG"
          echo "Changelog: $RELEASE_LOG"

      - name: Create Release
        id: create-release
        uses: actions/github-script@v6
        with:
          script: |
            const { data } = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: `${process.env.RELEASE_TAG}`,
              name: `Steam Art Manager ${process.env.RELEASE_TAG}`,
              body: `${process.env.RELEASE_LOG}`,
              draft: true,
              prerelease: false
            })
            return data.id
        env:
          RELEASE_TAG: $RELEASE_TAG
          RELEASE_LOG: $RELEASE_LOG

  build-tauri-linux:
    needs: create-release
    permissions:
      contents: write

    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Rust Stable
        uses: dtolnay/rust-toolchain@stable

      - name: Install Dependencies (Linux Only)
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
      - name: install frontend dependencies
        run: npm install

      - name: Build App
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        with:
          releaseId: ${{ needs.create-release.outputs.release_id }}

  build-tauri-windows:
    needs: create-release
    permissions:
      contents: write

    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Rust Stable
        uses: dtolnay/rust-toolchain@stable

      - name: install frontend dependencies
        run: npm install

      - name: Build App
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        with:
          releaseId: ${{ needs.create-release.outputs.release_id }}

  update-gist:
    needs: [build-tauri-linux, build-tauri-windows]
    permissions:
      contents: write
    runs-on: ubuntu-20.04
    
    steps:
      - name: Date
        run: echo "DATE=$(date +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV

      - name: Read Update Signature - Linux
        id: readLinux
        uses: juliangruber/read-file-action@v1
        with:
          path: "https://github.com/Tormak9970/Steam-Art-Manager/releases/download/untagged-${{ needs.create-release.release_id }}/steam-art-manager_${{ needs.create-release.outputs.version }}_amd64.AppImage.tar.gz.sig"
      
      - name: Read Update Signature - Windows
        id: readWindows
        uses: juliangruber/read-file-action@v1
        with:
          path: "https://github.com/Tormak9970/Steam-Art-Manager/releases/download/untagged-${{ needs.create-release.release_id }}/Steam.Art.Manager_${{ needs.create-release.outputs.version }}_x64_en-US.msi.zip.sig"

      - name: Write Update Gist
        uses: sergeysova/gist-write-action@v1
        with:
          gist_id: a72aa3b7232033772d80b0ed86303f01
          file_name: sarm_version.json
          content: |
            {
              "version": "v${{ needs.create-release.outputs.version }}",
              "notes": "${{ needs.create-release.outputs.change_log }}",
              "pub_date": "$DATE",
              "platforms": {
                "linux-x86_64": {
                  "signature": "${{ steps.readLinux.output.content }}",
                  "url": "https://github.com/Tormak9970/Steam-Art-Manager/releases/download/v${{ needs.create-release.outputs.version }}/steam-art-manager_${{ needs.create-release.outputs.version }}_amd64.AppImage.tar.gz"
                },
                "windows-x86_64": {
                  "signature": "${{ steps.readWindows.output.content }}",
                  "url": "https://github.com/Tormak9970/Steam-Art-Manager/releases/download/v${{ needs.create-release.outputs.version }}/Steam.Art.Manager_${{ needs.create-release.outputs.version }}_en-US.msi.zip"
                }
              }
            }
            
  publish-release:
    needs: [update-gist]
    permissions:
      contents: write
    runs-on: ubuntu-20.04

    steps:
      - name: Publish Release
        id: publish-release
        uses: actions/github-script@v6
        env:
          release_id: ${{ needs.create-release.outputs.release_id }}
        with:
          script: |
            github.rest.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: process.env.release_id,
              draft: false,
              prerelease: false
            })
  
